import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
dynamic_title = false
opacity = 0.85
title = "hey"

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 2
y = 2

[keyboard]
bindings = [
	{ key = "PageDown", mods = "Shift", action = "ScrollPagedown" },
	{ key = "PageUp",   mods = "Shift", action = "ScrollPageUp" },
	{ key = "Return",   mods = "Alt",     action = "CreateNewWindow" },
]
